### PR TITLE
Add GraphQL support

### PR DESCRIPTION
**Pull request by teriu**
See http://dev.apollodata.com/react/webpack.html for further details

### CODE REVIEW

**Comment by teriu** [comment]
Hmm, need to add this to the README too.

**Comment by hally9k** [comment]
I'll get to look through this over the weekend hopefully... Maybe I can add to the readme..

**Comment by hally9k** [comment]
@teriu "Remove semi-colons from JS files" ☹️

**Comment by teriu** [comment]
My package is way ahead now... I'm going to close this for now.

**Comment by hally9k** [comment]
... I am about to merge it in and have a jam.

**Comment by teriu** [comment]
Up to you - as is/where is :)

**Pull request closed without merging**
